lib/wovnrb/store.rb, spec/spec_helper.rb, test/services/url_test.rb
Tests does not run on my Ubuntu. Mac OSX HFS is case-insensitive Filesystem by default.
https://blog.breadncup.com/2010/04/16/mac-osx-hfs-is-case-insensitive-filesystem-by-default/
=> Decapitalize string in require.

lib/wovnrb.rb
This fix enables all rack based applications to use wovnrb, not only Rails.
```ruby
require 'sinatra'
require 'wovnrb'
use Wovnrb::Interceptor, {
:user_token => 'IRb6-',
'secret_key' => 'secret',
}
get '/' do
'<html><body>Hello world!</body></html>'
end
```
=> Fix for using as normal rack middleware.

lib/wovnrb/store.rb
wovnrb gets no data when non https url is set to api_url property.
=> Do not use "use_ssl" when http.scheme is "http".

lib/wovnrb.rb, lib/wovnrb/html_replacers/script_replacer.rb
Script tag of https://wovn.io is as follows. "version" parameter is always empty. We should do "require 'wovnrb/version'" in wovnrb.rb.
```html
<script src="//j.wovn.io/1" async="true" data-wovnio="key=2Wle3&amp;backend=true&amp;currentLang=en&amp;defaultLang=en&amp;urlPattern=path&amp;version="> </script>
```
There are some tests about this. But "bundle exec rake test" command seems to load all modules, so the tests are working well.
=> "version" parameter is always empty in wovn script tag.

lib/wovnrb/lang.rb, test/lib/lang_test.rb
When accessing "http://wovn.io/ja", relative link like "policy" is replaced with "jacontact". This pull request fixes this.
=> There is some case that the slash is needed.

.gitignore, lib/wovnrb/headers.rb, lib/wovnrb/store.rb, test/lib/headers_test.rb
When "use_proxy" option is true, wovnrb uses env['HTTP_X_FORWARDED_HOST'] instead of env['HTTP_HOST'] and env['SERVER_NAME'].
This function is for an application with reverse proxy.
Automatical using env['HTTP_X_FORWARDED_HOST'] has some security risk, so I have implemented this as an option.
=> Implement use_proxy option.

lib/wovnrb/headers.rb, test/lib/headers_test.rb
https://github.com/WOVNio/wovnjava/pull/39
In the following case, query should be empty string.
* query parameter: "p"
* page url: "localhost/?q=1"
=> Query parameter should be empty when query setting is not matching.

lib/wovnrb/headers.rb, test/lib/headers_test.rb
When url_pattern is subdomain and request URL is 'https://wovn.io' (no language code), HTTP_REFERER that the application gets was 'https:/wovn.io' and it was broken. I fixed the bug.
=> HTTP_REFERER was broken.

test/lib/text_caches/cache_base_test.rb
CacheBaseTest#test_get_single_without_set test sometimes fails.
>   1) Failure:
> CacheBaseTest#test_get_single_without_set [/Users/masahiroiuchi/github/wovnrb/test/lib/text_caches/cache_base_test.rb:27]:
> RuntimeError expected but nothing was raised.
It is reproduced by the following command.
> $ bundle exec rake test TESTOPTS="--seed=63769"
* wovnrb tests are done randomly.
* Wovnrb::CacheBase needs not to be initialized for CacheBaseTest#test_get_single_without_set test passing.
=> Fix sometimes failed test.

wovnrb.gemspec
It's not alpha version now. The description seems to be displayed on RubyGems.org.
https://rubygems.org/gems/wovnrb
=> Update description of wovnrb.gemspec.

wovnrb.gemspec
Rails uses same version of activesupport. Current wovnrb works only with Rails 4.2.6 application.
=> Fix activesupport version.

wovnrb.gemspec
Ruby 1.9.3 tests were failing because of some gems update.
To maintain Ruby 1.9.3 compatibility I pined down the compatible version of the gems that were causing problems.
=> Hotfix/travis ruby 1.9.3 tests

test/lib/html_replacers/image_replacer_test.rb, test/lib/html_replacers/text_replacer_test.rb, test/lib/lang_test.rb, test/lib/text_caches/memory_cache_test.rb
Warning is this.
```
bundle exec rake test
Run options: -p --seed 53044
***************************************************Use assert_nil if expecting nil from wovnrb/test/lib/html_replacers/image_replacer_test.rb:88:in `test_replace_absolute_path'. This will fail in MT6.
*Use assert_nil if expecting nil from wovnrb/test/lib/html_replacers/image_replacer_test.rb:68:in `test_replace_root_path'. This will fail in MT6.
*Use assert_nil if expecting nil from wovnrb/test/lib/html_replacers/image_replacer_test.rb:48:in `test_replace_relative_path'. This will fail in MT6.
************Use assert_nil if expecting nil from wovnrb/test/lib/lang_test.rb:207:in `test_add_lang_code_nil_href'. This will fail in MT6.
*********Use assert_nil if expecting nil from wovnrb/test/lib/lang_test.rb:81:in …
```
=> Fix assert warnings.

lib/wovnrb/store.rb
Hash.stringify_keys! method is extend by ActiveSupport.
So need add require 'active_support/core_ext'.
Pass test case, but this error displayed with sinatra.
Because `require 'active_support/core_ext'` is running somewhere only in the test.
```
Boot Error
Something went wrong while loading config.ru
NoMethodError: undefined method `stringify_keys!' for {"ja"=>"staging-ja"}:Hash
/home/hiroshi/git/wovn/wovnrb/lib/wovnrb/store.rb:146:in `settings'
/home/hiroshi/git/wovn/wovnrb/lib/wovnrb.rb:25:in `initialize'
/home/hiroshi/git/wovn/wovnrb-sinatra/vendor/bundle/ruby/2.1.0/gems/rack-1.6.5/lib/rack/builder.rb:86:in `new'
/home/hiroshi/git/wovn/wovnrb-sinatra/vendor/bundle/ruby/2.1.0/gems/rack-1.6.5/lib/rack/builder.rb:86:in `block in use' …
```
=> Fix to work with sinatra

circle.yml, lib/wovnrb/html_replacers/replacer_base.rb, test/lib/html_replacers/replacer_base_test.rb
Related to:
- Segmentation fault when creating `wovn-src` comment node
Creating a comment node needs to be done from the node's document instead
of the node itself.
=> Fix segmentation introduced with release 0.2.11.

lib/wovnrb/headers.rb, test/lib/headers_test.rb
Add a request env value to make visible the language detected by WovnRB: `wovnrb.target_lang`.
Some users want to know the target language detected by WovnRB. This is now possible by looking at the `wovnrb.target_lang` value in the request environment that WovnRB sends to the application (`request.env['wovnrb.target_lang']`).
=> 	Add wovnrb.target_lang env to be used in user application

lib/wovnrb/headers.rb, test/lib/headers_test.rb
Do not add lang code in Location header if default language is selected.
User needs the fix on 0.2.07 version so I replicated this fix at branch hotfix/0.2.07_default_lang_out_location and I will make a specific tag for them to use.
=> do not add language code to location header when target language is same as default language

Gemfile, wovnrb.gemspec
Avoid activesupport restriction problem.
Current restriction does not seem to work and users using ruby version greater than 2.2.2 can't install active support higher than 5.0.0. I think it is fine to remove restriction and let bundle do its job when calculating dependencies (after all wovnrb is not restricted to activesupport lesser than 5.0.0).
=> remove restrictions on activesupport

lib/wovnrb.rb, test/lib/wovnrb_test.rb
Do nothing for AMP content
WOVN widget does not support AMP content, so we should ignore those pages. If we don't ignore them the pages could be added on WOVN.io (e.g. if page is directly open in browser for testing). AMP content can be detected by looking at the HTML tag (https://www.ampproject.org/docs/tutorials/create/basic_markup).
=> Ignore AMP content.

lib/wovnrb.rb, lib/wovnrb/api_data.rb, lib/wovnrb/store.rb, test/lib/api_data_test.rb, test/lib/store_test.rb, test/lib/wovnrb_test.rb, test/test_helper.rb, wovnrb.gemspec
The user can modify the Rack::Request object to change the token on a per-request basis
```
Rack::Request.new(env).update_param('wovn_token', 'test1')
```
I will add and fix the tests!!
This is for cloud CMS services who want to be able to load a token per user based on which website they are serving.
=> Add the ability for users to support different tokens for different requests

lib/wovnrb/lang.rb, test/lib/lang_test.rb
issues link https://github.com/WOVNio/equalizer/issues/7361
currently when user use encoded url as href, wovn.rb return decoded url as the href.
ex: 
when user use this encoded japanese path.
```
<a href="http://ccc.com:4300/%E3%83%86%E3%82%B9%E3%83%88/DxA9J">this is encoded japanese path</a></li>
```
we return decoded url with wovnrb
```
<a href="http://ccc.com:4300/テスト/DxA9J">this is encoded japanese path</a>
```
we should keep original encoding and decoding for href as much as possible.
this probrem come from nokogiri. nokogiri encode href automatically when we use `#to_html` to dom object made from nokogiri. so we had decoded all href.  so when we use encoded href, we return decoded href like below flow.
1. we specify encoded url as href.
1. nokogiri encode this url, but this url …
=> Keep original encoding and decoding for href

lib/wovnrb/lang.rb, test/lib/lang_test.rb
this pr is bugfix of https://github.com/WOVNio/wovnrb/pull/95
Not only `a`tag but also `link` has `href` attributes. so I fixed to handle all tags with `href`
=> Handle all href for creating_index

lib/wovnrb.rb, lib/wovnrb/version.rb, test/lib/wovnrb_test.rb
Sometimes users need to set the project token dynamically. We supported this with wovn_token which allows the user to set the token on a per-request basis.
In the same way, sometimes users don't want WOVNrb to make any API call (or do any HTML transformations). To support this, I've added the wovn_disable parameter. If the user sets the parameter to true:
`Rack::Request.new(env).update_param('wovn_disable', true) `
Then WOVNrb will not make an API call and will not modify the HTML. (It will still mask the headers)
The reason I think we should support this is because it will reduce the number of unnecessary requests to our API, and it will increase the speed of WOVNrb when the user wants to disable it.
Please tell me if you can think of any more test cases or if you want me to stop using …
=> Feature Proposal: Add wovn_disable parameter

lib/wovnrb.rb, lib/wovnrb/settings.rb, lib/wovnrb/store.rb, test/lib/wovnrb_test.rb
Relate: https://github.com/WOVNio/wovnrb/pull/94
The user can modify the Rack::Request object to change the token on a per-request basis.
This is example for sinatra. Also other rack application can do it by simuler way.
```
require 'sinatra/base'
class Server < Sinatra::Base
get '/dynamic_ignore' do
request.update_param('wovn_ignore_paths', ['/dynamic_ignore', '/other_rule'])
erb :index
end 
end
```
`wovn_token` and this one can be used together.
=> Add the ability for users to support different ignore_paths settings for different requests

lib/wovnrb/headers.rb, test/lib/headers_test.rb, test/lib/lang_test.rb, test/test_helper.rb
Implement support for HTTP_X_FORWARDED_PROTO or other proxy's header.
When there is some special headers, use the protocol instead of rack's request url.
You can check headers at https://github.com/rack/rack/blob/master/lib/rack/request.rb#L188.
=> Implement support for HTTP_X_FORWARDED_PROTO or other proxy's header.

lib/wovnrb/html_replacers/link_replacer.rb, test/lib/html_replacers/link_replacer_test.rb
Prevent replacing any link that is javascript code
Only the case of `href="javascript:void(0);"` was handle, but any javascript code should be handled.
=> prevent replacing any link that is javascript code

lib/wovnrb.rb, test/lib/wovnrb_test.rb
For issue https://github.com/WOVNio/equalizer/issues/10957
Make sure to always include widget, even if no values are found for the page.
I'm not 100% sure that this will solve the problem at Shushugirl (some pages don't get automatically added), but I believe that this behavior is correct for wovnrb regardless.
=> Include widget snippet also for when values are zero.

lib/wovnrb.rb, test/lib/wovnrb_test.rb
Adds fix to prevent Nokogiri from adding extra new lines that could break the page html for some frameworks (ex: Nuxt)
=> No extra new line when outputting html

lib/wovnrb/headers.rb, lib/wovnrb/html_replacers/link_replacer.rb, lib/wovnrb/lang.rb, test/lib/html_replacers/link_replacer_test.rb, test/test_helper.rb, wovnrb.gemspec
Support `base` tag
> The HTML <base> element specifies the base URL to use for all relative URLs contained within a document. There can be only one <base> element in a document.
> -- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
=> Add base href tag support

README.md, lib/wovnrb.rb, lib/wovnrb/helpers/nokogumbo_helper.rb, lib/wovnrb/html_replacers/image_replacer.rb, lib/wovnrb/html_replacers/input_replacer.rb, lib/wovnrb/html_replacers/meta_replacer.rb, lib/wovnrb/html_replacers/replacer_base.rb, lib/wovnrb/html_replacers/text_replacer.rb, lib/wovnrb/lang.rb, lib/wovnrb/store.rb, lib/wovnrb/version.rb, test/lib/html_replacers/image_replacer_test.rb, test/lib/html_replacers/input_replacer_test.rb, test/lib/html_replacers/meta_replacer_test.rb, test/lib/html_replacers/replacer_base_test.rb, test/lib/html_replacers/text_replacer_test.rb, test/lib/lang_test.rb, test/lib/wovnrb_test.rb, test/test_helper.rb
Prevent bug where multiple snippets are inserted and HTML structure is corrupted by wovnrb intercepting HTML fragment.
This PR detects HTML fragments and parse them as is to avoid adding extra `<html>`, `head` and `body` tags with Nokogumbo.
Widget snippet is never added to HTML fragment .
HTML fragments are translated by default, user can disable it by setting option `translate_fragment` to `false`.
=> Handle HTML Fragments

wovnrb.gemspec
With recent update of Nokogumbo to 2.0.0, test no longer pass. This
change is to keep using older version of Nokogumbo that passes the tests
until investigation on using Nokogumbo.
Even with Nokogumbo 1.3.0 test are no longer passing. I guess it comes from https://github.com/WOVNio/wovnrb/pull/123 which overrides one Nokogumbo method.
=> Use latest compatible Nokogumbo version

lib/wovnrb/api_translator.rb, lib/wovnrb/store.rb, test/lib/api_translator_test.rb, test/lib/store_test.rb
Directly use local server for Translation API in dev mode (avoid extra setup).
Current Translation API does not compress content in development environment, so I added that case to `ApiTranslator`.
=> Dev Mode with Local Translation API

lib/wovnrb/services/html_converter.rb, test/lib/services/html_converter_test.rb, test/lib/wovnrb_test.rb, wovnrb.gemspec
Correctly escape `data-wovnio` attribute in the widget snippet when using fallback method.
wovnrb's fallback method is currently inserting a snippet that is incorrectly escaped twice like this
```
<script src="//j.wovn.io/1" async="true" data-wovnio="key=Gl5Niu&amp;amp;backend=true&amp;amp;currentLang=en&amp;amp;defaultLang=en&amp;amp;urlPattern=path&amp;amp;langCodeAliases={}&amp;amp;version=WOVN.rb_2.0.1" data-wovnio-type="fallback_snippet">
```
With this change, the content of `data-wovnio` will only be escaped once, like this
```
<script src="//j.wovn.io/1" async="true" data-wovnio="key=Gl5Niu&amp;backend=true&amp;currentLang=en&amp;defaultLang=en&amp;urlPattern=path&amp;langCodeAliases={}&amp;version=WOVN.rb_2.0.1" data-wovnio-type="fallback_snippet">
```
This PR also adds the …
=> [FIX] Correctly escape data-wovnio attribute in snippet

lib/wovnrb/store.rb, lib/wovnrb/version.rb
Raise default timeout to 1.0 seconds for API requests.
Related issue: https://github.com/WOVNio/equalizer/issues/16976
Also bump patch version.
=> Change default API timeout to 1 second

lib/wovnrb.rb, lib/wovnrb/railtie.rb
Allow Rails user to add middleware before WOVN.rb middleware for a better control of WOVN.rb. For instance, having custom middleware called before WOVN.rb will allow from disabling WOVN.rb before any environment alterations are performed by WOVN.rb (WOVN.rb remove language specific information from environment sent to next middlewares).
By default behavior remains same. If user does not add WOVN.rb middleware themselves, then WOVN.rb railtie will insert the middleware on top of the stack.
Following is a Rails setup example.
`config/application.rb`
```
class TestMiddleware
def initialize(app)
@app = app
end
def call(env)
Rack::Request.new(env).update_param('wovn_disable', true)
return @app.call(env)
end
end
module MyApp
class Application < Rails::Application …
```
=> Allow for Placing Rack Middleware before WOVN.rb Middleware on Rails

.rubocop_todo.yml, README.md, lib/wovnrb/api_translator.rb, lib/wovnrb/headers.rb, lib/wovnrb/lang.rb, lib/wovnrb/services/html_converter.rb, lib/wovnrb/store.rb, test/lib/api_translator_test.rb, test/lib/headers_test.rb, test/lib/lang_test.rb, test/lib/services/html_converter_test.rb, test/lib/store_test.rb, test/test_helper.rb
Add `lang_param_name` option support.
`lang_param_name` option allows user to customize the query parameter user to store the language information when `url_pattern_name` is set to `query`. Previous, `wovn` was the only available value for the name of the query parameter to store the language information. `wovn` remains the default value for retro compatibility.
=> [IS-376] Add support for `lang_param_name`

lib/wovnrb/railtie.rb, lib/wovnrb/version.rb
Ensure that interception happens before `Rack::Deflater` compression.
`Rack::Deflater` compresses response rendering WOVN.rb inable to translate content. This change ensures that WOVN.rb middleware installs itself after `Rack::Defleter` middleware so that it can process data before `Rack::Deflater` compresses it.
=> Add Rack::Deflater Support in railtie.rb

README.md, lib/wovnrb.rb, lib/wovnrb/headers.rb, lib/wovnrb/settings.rb, lib/wovnrb/version.rb, test/lib/headers_test.rb, test/lib/wovnrb_test.rb, test/test_helper.rb
Fully ignore paths that exist with (not added by WOVN) language code
If user set an ignore path with a language code, WOVN.rb assume it is a genuine path and does nothing.
=> Fully ignore paths that exist with (not added by WOVN) language code

lib/wovnrb/store.rb, lib/wovnrb/version.rb, test/lib/store_test.rb
Because we switched to use `https` in dev mode recently
=> Return wovn_host of `dev-wovn.io` without port in dev mode

lib/wovnrb/railtie.rb, lib/wovnrb/version.rb
https://wovnio.atlassian.net/browse/SUP-713
We're relying on private code inside rails for checking if the middleware is installed already. But the signature of this private method changed in a newer version. This fix is just a hack to stop it crashing (so it won't behave correctly with Deflater). I will look for a better way of doing this afterwards.
https://github.com/rails/rails/commit/fedde239dcee256b417dc9bcfe5fef603bf0d952#diff-17b775617b7196b0e9851f109b0b3269d3e41a1a0893daa1832bdfb847f71477
=> fix: [SUP-713] temporary fix for railtie middleware check not working on newer rails

docker/rails/TestSite/app/controllers/custom_response_controller.rb, docker/rails/TestSite/config/routes.rb
https://wovnio.atlassian.net/browse/ST-902
In the test docker website, there is now a `/custom_response` route. You can send it a request like
```
GET /custom_response
body:
{
"response": {
"body": "foo2",
"content-type": "text/html",
"status": 200,
"headers": { "X-WovnTest": "Foo" }
}
}
```
and it will generate the response according to these parameters. Our tests can use this to change the HTML and headers, rather than needing to add new test scenarios to the docker directly.
```
curl --verbose --location --request GET 'http://localhost:4000/custom_response' \
> --header 'Content-Type: application/json' \
> --data-raw '{
>     "response": {
>         "body": "foo2",
>         "content-type": "text/html",
>         "status": 201,
>         "headers": { "X-WovnTest": "Foo" }
>     }
> }' …
```
=> [ST-902] Add custom_response route to test docker, allowing the tests to control the website externally.

lib/wovnrb/railtie.rb, lib/wovnrb/version.rb
Forgot to set a default value in https://github.com/WOVNio/wovnrb/pull/170
When `install_middleware` is not specified in wovnrb config => true (easier for existing customers to upgrade)
When `install_middleware` is set to true or false in wovnrb config => use config value
=> fix: set default value of install_middleware to be true

README.en.md, lib/wovnrb/api_translator.rb, lib/wovnrb/store.rb, lib/wovnrb/version.rb, test/lib/api_translator_test.rb
https://wovnio.atlassian.net/browse/ST-1100
We currently gzip the request to html swapper. There is now a compress_api_request setting that can be set to false to disable this.
This is only to make it easier to use MockServer to assert the incoming request as JSON in integration tests.
=> feature:  [ST-1100] Add compress_api_request setting, for sending uncompressed html swapper requests for testing

lib/wovnrb/api_translator.rb, lib/wovnrb/version.rb, test/lib/api_translator_test.rb
https://wovnio.atlassian.net/browse/ST-914
This PR wraps the decompress of response text in a try catch block.
We assume the response is plain text if we cannot use gzip to uncompress it properly.
=> add default fallback logic to treat html-swapper response as plain text

Rakefile
Hate to do this but with this option enabled, if there are invalid UTF-8 byte sequences in the diff the test will crash (can happen for tests that deals with gzipped request body stubs). It is confusing if you are not familiar with this behavior.
=> remove -p option for minitest

lib/wovnrb/store.rb, lib/wovnrb/version.rb, test/lib/api_translator_test.rb, test/lib/headers_test.rb, test/lib/store_test.rb, test/lib/wovnrb_test.rb
In https://github.com/WOVNio/wovnrb/pull/215 , Rubocop changed from `"^(?<lang>[^.]+)\."` to `'^(?<lang>[^.]+).'`.
String in Ruby has the following behavior. Notice that `"` and `'` has different behavior.
- `"\\."` == `'\.'`
- `"\."` == `'.'`
To find subdomain's lang code, `.` character should be after language code.
So, regexp should be `'^(?<lang>[^.]+)\.'` .
I changed all hard coded regexp.
=> Fix regexp

lib/wovnrb/url_language_switcher.rb, lib/wovnrb/version.rb, test/lib/url_language_switcher_test.rb
Bug: URLs like `http://site.com/dir/en/page.html` would be incorrectly modified to `http://site.com/dir/page.html`. We should only handle the "wovn" lang code like `http://site.com/en/dir/page.html`. The user is allowed to use lang codes in other directories.
=> fix: Removing lang codes with path pattern only removes from the first path segment

.rubocop.yml, Gemfile, lib/wovnrb/lang.rb, lib/wovnrb/version.rb, wovnrb.gemspec
This changes es-RA to es-AR
See https://wovnio.slack.com/archives/C03AA9V3E/p1674539995055339 for more information
Also, without changing master, rubocop now fails locally and on CI?!  I adjusted how we import dev dependencies to make rubocop happy. Feedback welcome.
=> fix: change es-RA to es-AR

lib/wovnrb/services/html_converter.rb, lib/wovnrb/version.rb, test/lib/services/html_converter_test.rb
Follow-up to #233.
Fixes issue where pages that don't need translation (e.g. pages displayed in default language) have hreflangs inserted.
=> fix: [ST-2294] Hreflangs are inserted for pages that don't need translation

lib/wovnrb.rb, lib/wovnrb/store.rb, lib/wovnrb/version.rb, test/lib/wovnrb_test.rb
https://wovnio.atlassian.net/browse/ST-2310
Adds support for `use_cookie_lang` setting, which allows the backend to return `302 Found` response if a cookie language is set to a target language and when the visited URL is in the default language.
For example, when the following URL is accessed:
```
http://example.com/foo
```
and cookie language is set to `ja`, then the URL will be redirected to:
```
http://example.com/ja/foo
```
=> feat: [ST-2310] Support `use_cookie_lang` setting
