WOVNio/wovnrb

circle.yml

Fixed CircleCI error.

---

.travis.yml

* Do "gem update bunder".
* Remove script.

Fix Travis CI error.

---

lib/wovnrb/store.rb
test/lib/headers_test.rb
test/lib/wovnrb_test.rb
wovnrb.gemspec

Do not use old server. Use new API server.

Use API server.

---

lib/wovnrb.rb
lib/wovnrb/store.rb
test/lib/store_test.rb

Fix url_pattern_reg parameter bug.

---

lib/wovnrb.rb
test/lib/wovnrb_test.rb

Please see also #13 and https://github.com/WOVNio/wovnphp/issues/7
Rewrite URL in form tag's action property.
* When method is "get" or "", and url_pattern is "query", URL in action property is rewritten.
* When method is not "get" and """, or url_pattern is not "query", hidden parameter is inserted to the form.
And I changed Wovnrb::STORE from class constant to instance variable. This is for test and for gettext-like feature.

Should rewrite URLs in form tag's action property.

---

lib/wovnrb/lang.rb
test/lib/lang_test.rb

Support Bulgarian.

---

.travis.yml

2 minutes => 1 minute
https://travis-ci.org/WOVNio/wovnrb/builds

Cache Dependencies on Travis CI.

---

lib/wovnrb/headers.rb
test/lib/headers_test.rb

Remove language code from HTTP_REFERER when url_pattern is path.

---

test/lib/api_data_test.rb
test/test_helper.rb
wovnrb.gemspec

Code coverage is 87.81% now. We can check it on CircleCI.

Check code coverage.

---

.travis.yml
circle.yml
test/lib/html_replacers/image_replacer_test.rb
test/lib/html_replacers/meta_replacer_test.rb
test/lib/html_replacers/replacer_base_test.rb
test/lib/html_replacers/text_replacer_test.rb
test/lib/lang_test.rb
test/lib/text_caches/memory_cache_test.rb

Do tests with the following Ruby versions and add magic comment to some test files.
* Ruby 2.3.0
* Ruby 2.2.0
* Ruby 2.0.0
* Ruby 1.9.3

Add tests of multiple ruby versions.

---

lib/wovnrb/lang.rb
test/lib/lang_test.rb
wovnrb.gemspec

https://github.com/WOVNio/equalizer/issues/1218

correct chinese code for hreflang

---

lib/wovnrb/html_replacers/link_replacer.rb
test/lib/html_replacers/link_replacer_test.rb
wovnrb.gemspec

Purpose/goal of PR (Issue #)
To ignore mustache for angualarjs
comments
Angularjs change url inside href when mustache exists, so not change anything if mustache exists

ignore mustache

---

lib/wovnrb/html_replacers/html_text_replacer.rb
test/lib/html_replacers/html_text_replacer_test.rb

Fix an unexpected case for unballanced src and dst for unified values (see tests).

add case for unballanced src and dst and fix code

---

wovnrb.gemspec

https://github.com/WOVNio/equalizer/issues/3066
Update nokogumbo to 1.4.1 so that client can use wovnrb

updating nokogumbo

---

README.md
lib/wovnrb/store.rb
test/lib/store_test.rb
test/test_helper.rb

we don't need secret_key anymore

remove secret_key

---

lib/wovnrb.rb
lib/wovnrb/html_replacers/input_replacer.rb
lib/wovnrb/lang.rb
test/lib/html_replacers/input_replacer_test.rb

Replace input value attribute unless it's text or search

Input Replacer

---

lib/wovnrb/html_replacers/link_replacer.rb
test/lib/html_replacers/link_replacer_test.rb
test/lib/lang_test.rb

Ignore javascript:void(0) in anchor tags href

Ignore javascript links

---

lib/wovnrb/html_replacers/image_replacer.rb
test/lib/html_replacers/image_replacer_test.rb

Fix wrong assemble URL when pathname parameter is empty.
x http://hostname:8888image.png
o http://hostname:8888/image.png

Fix assembly error of image URL

---

test/lib/lang_test.rb

add langCodeAliases to new test generated html code

---

lib/wovnrb/html_replacers/image_replacer.rb
lib/wovnrb/lang.rb
test/lib/html_replacers/image_replacer_test.rb

Use if host aliases are specified at image replace.

Supports replace image with host alias

---

lib/wovnrb/lang.rb
test/lib/headers_test.rb
test/lib/lang_test.rb

add Nepali support to wovnrb

---

lib/wovnrb/version.rb

release 0.2.15

---

README.md
lib/wovnrb/api_data.rb
lib/wovnrb/html_replacers/script_replacer.rb
lib/wovnrb/railtie.rb
lib/wovnrb/store.rb
test/lib/api_data_test.rb
test/lib/html_replacers/script_replacer_test.rb
test/lib/store_test.rb
test/lib/wovnrb_test.rb
test/test_helper.rb

Refer to project token instead of user token.
User can still use user_token, but it will be placed into project_token setting.

Rename user_token config into project_token

---

lib/wovnrb/html_replacers/input_replacer.rb
test/lib/html_replacers/input_replacer_test.rb

wovnrb wasn't translating placeholder attribute in input tags.
So, I support it.

Handle input placeholder 

---

.travis.yml
lib/wovnrb/store.rb
lib/wovnrb/text_caches/memory_cache.rb
wovnrb.gemspec

I support Rails 5.x and Ruby 2.4.x

Support Rails 5.x and Ruby 2.4.x

---

lib/wovnrb/html_replacers/link_replacer.rb
test/lib/html_replacers/link_replacer_test.rb

skip adding lang code to file url
I will cherry pick this comment and add to master branch once this PR is approved

skip adding lang code to file url

---

lib/wovnrb/lang.rb
test/lib/lang_test.rb

Correctly add lang code with query pattern when url contains hash.

ensure query lang code is added before hash in url

---

lib/wovnrb/lang.rb
test/lib/lang_test.rb
test/lib/wovnrb_test.rb

Two fixes:
- Add the hreflang tag for the original language on every pages
- Correct the html lang= attribute with iso normalization

Add hreflang for original lang, fix html lang with iso normalization

---

lib/wovnrb.rb
test/lib/wovnrb_test.rb
test/test_helper.rb

issue https://github.com/WOVNio/equalizer/issues/7359
we had forgotten to put back noscripts on amp. so  I just put back noscripts on amp.

Put back noscript for amp

---

.travis.yml
lib/wovnrb/version.rb

Update test version
because 2.2 or later is officially supported
https://wovn.io/support/ruby-library/
support
- 2.5
- 2.4
- 2.3
- 2.2

Update test version

---

circle.yml
wovnrb.gemspec

For this: https://github.com/WOVNio/wovnrb/network/dependencies#34578148

Upgrade dependency for security patch

---

lib/wovnrb.rb
test/lib/wovnrb_test.rb

Fix to not swap data if page is not published

Fix to not swap data if page is not published

---

lib/wovnrb/version.rb

Bump up 1.0.3

---

lib/wovnrb/version.rb
test/lib/wovnrb_test.rb

Version 1.0.6

---

README.md
lib/wovnrb/html_replacers/image_replacer.rb
lib/wovnrb/html_replacers/input_replacer.rb
lib/wovnrb/html_replacers/link_replacer.rb
lib/wovnrb/html_replacers/meta_replacer.rb
lib/wovnrb/html_replacers/replacer_base.rb
lib/wovnrb/html_replacers/script_replacer.rb
lib/wovnrb/html_replacers/text_replacer.rb
lib/wovnrb/lang.rb
lib/wovnrb/store.rb
test/lib/html_replacers/image_replacer_test.rb
test/lib/html_replacers/input_replacer_test.rb
test/lib/html_replacers/link_replacer_test.rb
test/lib/html_replacers/meta_replacer_test.rb
test/lib/html_replacers/replacer_base_test.rb
test/lib/html_replacers/text_replacer_test.rb

Implement custom ignore setting

Implement custom ignore setting

---

lib/wovnrb/html_replacers/link_replacer.rb
test/lib/html_replacers/link_replacer_test.rb

Localize links with `rel="canonical"` attributes for SEO purpose

Adds support for canonical links

---

test/lib/html_replacers/link_replacer_test.rb
test/lib/lang_test.rb

Clean up test

---

lib/wovnrb.rb
lib/wovnrb/store.rb
test/lib/api_data_test.rb
test/lib/headers_test.rb
test/lib/html_replacers/replacer_base_test.rb
test/lib/html_replacers/script_replacer_test.rb
test/lib/lang_test.rb
test/lib/services/wovn_logger_test.rb
test/lib/store_test.rb
test/test_helper.rb
wovnrb.gemspec

Refactor settings management in store.rb to avoid infinite looping errors and unwanted side effects.
- `Store.rb` now manages settings with separate functions divided by responsibility.
- When loading settings `@config_loaded = true` is set immediately to avoid infinite looping error
- (semi-related) Remove two redundant lines from `store.rb#initialize`
- (unrelated) Remove a `File.exists?` assertion from test.

Manage settings

---

lib/wovnrb/store.rb

DRY code
Hi!
Thank you for making useful lib!
I think Wovn is good service!!
I just want to be a little contribution!!
So making this pr :)

refactor Wovnrb::Store#valid_settings?

---

lib/wovnrb/store.rb
test/lib/services/html_converter_test.rb
test/lib/wovnrb_test.rb

Put back default value in store default settings for `wovn_dev_mode`
I removed dev mode then it came back and we suffer inconsistant default value on staging

set default value for 'wovn_dev_mode' setting

---

lib/wovnrb/services/html_converter.rb
lib/wovnrb/version.rb
test/lib/services/html_converter_test.rb

Fix 
Added 2 missing tests for this piece of code

Fix ignore form and hidden input

---

wovnrb.gemspec

Loosen bundler version restriction

---

README.md

Update supported version in README file

Update supported version in README file

---

lib/wovnrb/api_translator.rb
test/lib/api_translator_test.rb

Requests to API should not hit cache after wovnrb version is updated.

Include version number in cache key to API

---

lib/wovnrb/version.rb

bump up version

---

.rubocop_todo.yml
lib/wovnrb/headers.rb

Fix rubocop rules which have changed in newer versions of rubocop

Fix rubocop rules which have changed in newer versions of rubocop

---

wovnrb.gemspec

Update Nokogiri version for CVE-2019-5477
refs: https://github.com/sparklemotion/nokogiri/issues/1915

Update Nokogiri version for CVE-2019-5477

---

lib/wovnrb/headers.rb
test/lib/headers_test.rb

Fix problems of unintended match condition and not replace REQUEST_URI.

Fixed none encoded url params in REQUEST_URI

---

lib/wovnrb/headers.rb
lib/wovnrb/version.rb
test/lib/headers_test.rb

Upgrade version number

---

lib/wovnrb/headers.rb

Remove the redirection as it may be cached.
Removing substantially non-functioning code.

Remove browser language redirection

---

lib/wovnrb/lang.rb
lib/wovnrb/version.rb
test/lib/headers_test.rb
test/lib/lang_test.rb

https://wovnio.atlassian.net/browse/ST-3822
Add Khmer language support

Add Khmer language support

---

lib/wovnrb/version.rb
wovnrb.gemspec

https://wovnio.atlassian.net/browse/ST-891
Update some information in gemspec.
Some of these information are shown in https://rubygems.org/gems/wovnrb

Update gem info

---

docker/docker-compose.yml

https://wovnio.atlassian.net/browse/ST-699
See https://github.com/WOVNio/backend_library_integration_tests/pull/3

[ST-699] Use explicit docker network to help with circle CI integration tests

---

lib/wovnrb.rb
lib/wovnrb/api_translator.rb
lib/wovnrb/services/wovn_logger.rb
lib/wovnrb/version.rb
test/lib/api_translator_test.rb
test/lib/services/wovn_logger_test.rb
test/lib/store_test.rb

https://wovnio.atlassian.net/browse/ST-998
It adds a UUID4 to all request to the translation API (html-swapper). Unfortunately it's not exactly straightforward to inherent the UUID from the intercepted request via Rack, and it also require the uuid being enabled in the user's Rails setup. So it's decided it will generate its own UUID.

Add X-Request-Id

---

.rubocop.yml
lib/wovnrb.rb
lib/wovnrb/headers.rb
lib/wovnrb/helpers/nokogumbo_helper.rb
lib/wovnrb/lang.rb
wovnrb.gemspec

~Builds on #192~
It seems like it would be nice to have this library take up as few resources as possible, so I thought it might benefit from rubocop-performance. Feel free to reject.

Add rubocop-performance

---

lib/wovnrb/version.rb

Forgot to update version in https://github.com/WOVNio/wovnrb/pull/192

bump patch number to 3.4.1

---

lib/wovnrb/api_translator.rb
lib/wovnrb/store.rb
lib/wovnrb/version.rb
test/lib/api_translator_test.rb

https://wovnio.atlassian.net/browse/ST-1214
It now sends the payload in JSON format regardless of compressed or not.

change request to use always use JSON

---

docker/rails/TestSite/app/controllers/custom_response_controller.rb

tests: fix typo in custom response controller

---

lib/wovnrb.rb
lib/wovnrb/headers.rb
lib/wovnrb/lang.rb
lib/wovnrb/services/html_converter.rb
lib/wovnrb/services/html_replace_marker.rb
lib/wovnrb/version.rb
test/lib/services/html_converter_test.rb
test/lib/wovnrb_test.rb

https://wovnio.atlassian.net/browse/ST-1936
Implementation basically copied from 
https://github.com/WOVNio/Wovn.cs/blob/master/wovn.cs/Html/HtmlConverter.cs#L404
tests from https://github.com/WOVNio/Wovn.cs/blob/master/wovn.cs.Tests/Html/HtmlConverterTest.cs#L690

feature: [ST-1936] implement backend-wovn-ignore

---

lib/wovnrb.rb
lib/wovnrb/headers.rb
test/lib/headers_test.rb

refactor: Rename `Headers#path_lang` to `url_language`

---

lib/wovnrb/headers.rb
test/lib/services/html_replace_marker_test.rb

Import tests from https://github.com/WOVNio/wovnjava/pull/229.

test: Add tests to check multiple hidden inputs

---

lib/wovnrb.rb
lib/wovnrb/version.rb
test/lib/wovnrb_test.rb

https://wovnio.atlassian.net/browse/ST-2310
Wovnrb redirects to cookie lang URL only for GET request method.

fix: [ST-2310] Redirection only for get request method

---

.rubocop.yml
lib/wovnrb.rb
lib/wovnrb/api_translator.rb
lib/wovnrb/lang.rb
lib/wovnrb/settings.rb
lib/wovnrb/version.rb
test/lib/api_translator_test.rb
test/lib/lang_test.rb
test/lib/wovnrb_test.rb

https://wovnio.atlassian.net/browse/ST-3320
https://github.com/WOVNio/html-swapper/pull/1044

feature: [ST-3320] send response status code to html swapper
